### ISSUE TITLE
Error while docker-compose up --build

### ISSUE THREAD

**Issue by SirSerje** [rahil471/nodejs-mongo-docker-sample#2]
```
 /usr/local/lib/node_modules/pm2/node_modules/chokidar/index.js:150
myapp_1     |   async remove(item) {
myapp_1     |         ^^^^^^
myapp_1     | 
myapp_1     | SyntaxError: Unexpected identifier
myapp_1     |     at createScript (vm.js:56:10)
myapp_1     |     at Object.runInThisContext (vm.js:97:10)
myapp_1     |     at Module._compile (module.js:549:28)
myapp_1     |     at Object.Module._extensions..js (module.js:586:10)
myapp_1     |     at Module.load (module.js:494:32)
myapp_1     |     at tryModuleLoad (module.js:453:12)
myapp_1     |     at Function.Module._load (module.js:445:3)
myapp_1     |     at Module.require (module.js:504:17)
myapp_1     |     at require (internal/module.js:20:19)
myapp_1     |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Watcher.js:6:16)
nodejs-mongo-docker-sample_myapp_1 exited with code 1
```

**Comment by criticalfail** [comment]
Change docker file;
 `FROM node:boron` to `FROM node:carbon`
Version support issue, upgrade it

**Comment by SirSerje** [comment]
thanks! 👍
